/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica2_201602598;

import java.util.Stack;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import static javax.swing.JSplitPane.RIGHT;
import java.lang.Math.*;


/**
 *
 * @author Hector
 */
public class Calculadora extends javax.swing.JFrame {
Stack pila=new Stack();
private int longitud;
public static String[] log;
private int contador;
String dato,operacion,estado;
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        dato="";
        operacion="";
        estado="";
        log=new String[500];
        contador=1;
        longitud=0;
        this.setLocationRelativeTo(null);
        txtpila.setHorizontalAlignment(txtpila.RIGHT);
         txtnumero.setHorizontalAlignment(txtnumero.RIGHT);
          txtresultado.setHorizontalAlignment(txtresultado.RIGHT);
    }
    
    public void setLog(String dato){
        log[contador-1]=dato;
        contador++;
        /*if(log[contador-1]==null){
            log[contador-1]=dato;
        }else{
        String con=log[contador-1];
        log[contador-1]=con+";"+dato;
        }*/
    }
    
    public String[] obLog(){
        return log;
    }
    
    public String obLogi(int i){
        return log[i];
    }
    
    public int obLongitud(){
        return log.length;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        btnmultiplicacion = new javax.swing.JButton();
        btndivision = new javax.swing.JButton();
        btncos = new javax.swing.JButton();
        btnsuma = new javax.swing.JButton();
        btnresta = new javax.swing.JButton();
        btnsen = new javax.swing.JButton();
        btnraiz = new javax.swing.JButton();
        btnraizx = new javax.swing.JButton();
        btntan = new javax.swing.JButton();
        btnx2 = new javax.swing.JButton();
        btnxn = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        txtenter = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        txtnumero = new javax.swing.JTextField();
        txtresultado = new javax.swing.JTextField();
        txtpila = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora-201602598");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("3");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 60, 40));

        jButton3.setText("1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 60, 40));

        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 60, 40));

        jButton5.setText("6");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 60, 40));

        jButton6.setText("5");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 60, 40));

        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 60, 40));

        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 60, 40));

        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 60, 40));

        jButton10.setText("0");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 60, 40));

        jButton11.setText("+/-");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 60, 40));

        jButton12.setText(".");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 60, 40));

        jButton13.setText("2");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 60, 40));

        jButton14.setText("DEL");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 60, 30));

        btnmultiplicacion.setText("*");
        btnmultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmultiplicacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnmultiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 60, 40));

        btndivision.setText("/");
        btndivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndivisionActionPerformed(evt);
            }
        });
        getContentPane().add(btndivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 60, 40));

        btncos.setText("Cos");
        btncos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncosActionPerformed(evt);
            }
        });
        getContentPane().add(btncos, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 60, 40));

        btnsuma.setText("+");
        btnsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsumaActionPerformed(evt);
            }
        });
        getContentPane().add(btnsuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 60, 40));

        btnresta.setText("-");
        btnresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrestaActionPerformed(evt);
            }
        });
        getContentPane().add(btnresta, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 60, 40));

        btnsen.setText("Sen");
        btnsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsenActionPerformed(evt);
            }
        });
        getContentPane().add(btnsen, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 60, 40));

        btnraiz.setText("√");
        btnraiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnraizActionPerformed(evt);
            }
        });
        getContentPane().add(btnraiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 60, 40));

        btnraizx.setText("x√");
        btnraizx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnraizxActionPerformed(evt);
            }
        });
        getContentPane().add(btnraizx, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 60, 40));

        btntan.setText("Tan");
        btntan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntanActionPerformed(evt);
            }
        });
        getContentPane().add(btntan, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 60, 40));

        btnx2.setText("x^2");
        btnx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnx2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnx2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 60, 40));

        btnxn.setText("x^n");
        btnxn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxnActionPerformed(evt);
            }
        });
        getContentPane().add(btnxn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 60, 40));

        jButton25.setText("CLS");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 60, 40));

        txtenter.setText("ENTER");
        txtenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtenterActionPerformed(evt);
            }
        });
        getContentPane().add(txtenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 180, 30));

        jButton27.setText("LOG");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 120, 30));
        getContentPane().add(txtnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 380, 20));

        txtresultado.setEditable(false);
        getContentPane().add(txtresultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 380, 20));

        txtpila.setEditable(false);
        txtpila.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtpilaPropertyChange(evt);
            }
        });
        getContentPane().add(txtpila, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 380, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("Resultado");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 0));
        jLabel3.setText("Ingresar numero");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 0));
        jLabel4.setText("Pila");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/windows_10_green_2-wallpaper-1366x768.jpg"))); // NOI18N
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpilaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtpilaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpilaPropertyChange

    private void txtenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtenterActionPerformed
        // TODO add your handling code here:
        if(longitud==2){
            JOptionPane.showMessageDialog(null, "Pila llena", "Error", WARNING_MESSAGE);
            txtnumero.setText(null);
        }else{
         
        pila.push(Double.valueOf(txtnumero.getText()));
         txtpila.setText(txtnumero.getText());
        txtnumero.setText(null);
        longitud++;
        //setLog(txtpila.getText());
        //-----------------------------
        dato=txtpila.getText();
        operacion="push";
        String aux=estado;
        estado=txtpila.getText();
        this.setLog(dato+";"+operacion+";"+"["+aux+" , "+estado+"]");
        //this.setLog(dato+";"+operacion+";"+"["+estado+" , "+aux+"]");
        }
       
    }//GEN-LAST:event_txtenterActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        txtnumero.setText(txtnumero.getText()+"0");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        txtnumero.setText(txtnumero.getText()+"1");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        txtnumero.setText(txtnumero.getText()+"2");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtnumero.setText(txtnumero.getText()+"3");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        txtnumero.setText(txtnumero.getText()+"4");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        txtnumero.setText(txtnumero.getText()+"5");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        txtnumero.setText(txtnumero.getText()+"6");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        txtnumero.setText(txtnumero.getText()+"7");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        txtnumero.setText(txtnumero.getText()+"8");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        txtnumero.setText(txtnumero.getText()+"9");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        double temp=Double.valueOf(txtnumero.getText());
        double aux=temp;
        
        dato=txtnumero.getText();
        
        temp*=-1;
        txtnumero.setText(String.valueOf(temp));
          //------------------------------------------
     
    //dato=txtnumero.getText();
    operacion="Cambio de signo";
    estado=txtpila.getText();
    this.setLog(dato+";"+operacion+";"+estado);
    //-------------------------------------------
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void btnsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsumaActionPerformed
        if(longitud==2){
            double n1=(double)pila.pop();
     double n2=(double) pila.pop();
     double total=n1+n2;
     txtresultado.setText((String.valueOf(total)));
     txtpila.setText((String.valueOf(total)));
     pila.push(total);
    longitud=1;
    //setLog("+");
    //------------------------------------------
    dato="+";
    operacion="Suma";
    estado=txtpila.getText();
    this.setLog(dato+";"+operacion+";"+estado);
    //-------------------------------------------
    
        }else{
             JOptionPane.showMessageDialog(null, "Debe ingresar 2 numeros antes de operar"+String.valueOf(longitud), 
                 "Aviso", ERROR_MESSAGE);
      
        }
     /*try{
         double n1=(double)pila.pop();
     double n2=(double) pila.pop();
     double total=n1+n2;
     txtresultado.setText((String.valueOf(total)));
     txtpila.setText((String.valueOf(total)));
     pila.push(total);
     longitud=1;
     }catch(Exception e){
         JOptionPane.showMessageDialog(null, "Debe ingresar 2 numeros antes de operar"+String.valueOf(longitud), 
                 "Aviso", ERROR_MESSAGE);
         longitud=1;
     }*/
        
    }//GEN-LAST:event_btnsumaActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
         txtnumero.setText(txtnumero.getText()+".");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btnrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrestaActionPerformed
        // TODO add your handling code here:
        if(longitud==2){
         double n1=(double)pila.pop();
     double n2=(double) pila.pop();
     double total=n2-n1;
     txtresultado.setText((String.valueOf(total)));
     txtpila.setText((String.valueOf(total)));
     pila.push(total);
     longitud=1;
     //------------------------------------------
    dato="-";
    operacion="Resta";
    estado=txtpila.getText();
    this.setLog(dato+";"+operacion+";"+estado);
    //-------------------------------------------
    
     }else{
         JOptionPane.showMessageDialog(null, "Debe ingresar 2 numeros antes de operar"+String.valueOf(longitud), 
                 "Aviso", ERROR_MESSAGE);
        
     }
    }//GEN-LAST:event_btnrestaActionPerformed

    private void btnmultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmultiplicacionActionPerformed
        // TODO add your handling code here:
        if(longitud==2){
         double n1=(double)pila.pop();
     double n2=(double) pila.pop();
     double total=n1*n2;
     txtresultado.setText((String.valueOf(total)));
     txtpila.setText((String.valueOf(total)));
     pila.push(total);
     longitud=1;
     //------------------------------------------
    dato="*";
    operacion="Multiplicar";
    estado=txtpila.getText();
    this.setLog(dato+";"+operacion+";"+estado);
    //-------------------------------------------
    
     }else{
         JOptionPane.showMessageDialog(null, "Debe ingresar 2 numeros antes de operar"+String.valueOf(longitud), 
                 "Aviso", ERROR_MESSAGE);
        
     }
    }//GEN-LAST:event_btnmultiplicacionActionPerformed

    private void btndivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndivisionActionPerformed
        // TODO add your handling code here:
        if(longitud==2){
         double n1=(double)pila.pop();
     double n2=(double) pila.pop();
     double total=n2/n1;
     txtresultado.setText((String.valueOf(total)));
     txtpila.setText((String.valueOf(total)));
     pila.push(total);
     longitud=1;
     //------------------------------------------
    dato="/";
    operacion="Division";
    estado=txtpila.getText();
    this.setLog(dato+";"+operacion+";"+estado);
    //-------------------------------------------
    
     }else{
         JOptionPane.showMessageDialog(null, "Debe ingresar 2 numeros antes de operar"+String.valueOf(longitud), 
                 "Aviso", ERROR_MESSAGE);
         
     }
    }//GEN-LAST:event_btndivisionActionPerformed

    private void btnraizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnraizActionPerformed
        // TODO add your handling code here:
             try{
         double n1=(double)pila.pop();
     double total=Math.sqrt(n1);
     txtresultado.setText((String.valueOf(total)));
     txtpila.setText((String.valueOf(total)));
     pila.push(total);
     longitud=1;
     //------------------------------------------
    dato="√";
    operacion="Raiz Cuadrada";
    estado=txtpila.getText();
    this.setLog(dato+";"+operacion+";"+estado);
    //-------------------------------------------
    
     }catch(Exception e){
         JOptionPane.showMessageDialog(null, "Debe ingresar un numero para elevar"+String.valueOf(longitud), 
                 "Aviso", ERROR_MESSAGE);
         
     }
    }//GEN-LAST:event_btnraizActionPerformed

    private void btnx2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnx2ActionPerformed
        // TODO add your handling code here:
               try{
         double n1=(double)pila.pop();
     double total=Math.pow(n1, 2);
     txtresultado.setText((String.valueOf(total)));
     txtpila.setText((String.valueOf(total)));
     pila.push(total);
    longitud=1;
     //------------------------------------------
    dato="^2";
    operacion="Potencia 2";
    estado=txtpila.getText();
    this.setLog(dato+";"+operacion+";"+estado);
    //-------------------------------------------
    
     }catch(Exception e){
         JOptionPane.showMessageDialog(null, "Debe ingresar un numero para elevar"+String.valueOf(longitud), 
                 "Aviso", ERROR_MESSAGE);
         
     }
    }//GEN-LAST:event_btnx2ActionPerformed

    private void btnxnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxnActionPerformed
        // TODO add your handling code here:
         if(longitud==2){
         double n1=(double)pila.pop();
     double n2=(double) pila.pop();
     double total=Math.pow(n2, n1);
     txtresultado.setText((String.valueOf(total)));
     txtpila.setText((String.valueOf(total)));
     pila.push(total);
     longitud=1;
       //------------------------------------------
       double aux=n1;
    dato="^"+n1;
    operacion="Potencia "+n1;
    estado=txtpila.getText();
    this.setLog(dato+";"+operacion+";"+estado);
    //-------------------------------------------
    
     }else{
         JOptionPane.showMessageDialog(null, "Debe ingresar 2 numeros antes de operar"+String.valueOf(longitud), 
                 "Aviso", ERROR_MESSAGE);
         
     }
    }//GEN-LAST:event_btnxnActionPerformed

    private void btnraizxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnraizxActionPerformed
        // TODO add your handling code here:
            if(longitud==2){
         double n1=(double)pila.pop();
     double n2=(double) pila.pop();
     double total=Math.pow(n2, 1/n1);
     txtresultado.setText((String.valueOf(total)));
     txtpila.setText((String.valueOf(total)));
     pila.push(total);
     longitud=1;
     //------------------------------------------
       double aux=n1;
    dato=n1+"√";
    operacion="Raiz "+n1;
    estado=txtpila.getText();
    this.setLog(dato+";"+operacion+";"+estado);
    //-------------------------------------------
    
     }else{
         JOptionPane.showMessageDialog(null, "Debe ingresar 2 numeros antes de operar"+String.valueOf(longitud), 
                 "Aviso", ERROR_MESSAGE);
         
     }
    }//GEN-LAST:event_btnraizxActionPerformed

    private void btncosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncosActionPerformed
        // TODO add your handling code here:
               try{
         double n1=(double)pila.pop();
     double total=Math.cos(n1);
     txtresultado.setText((String.valueOf(total)));
     txtpila.setText((String.valueOf(total)));
     pila.push(total);
     //longitud=1;
      //------------------------------------------
    dato="Cos (radianes)";
    operacion="Coseno";
    estado=txtpila.getText();
    this.setLog(dato+";"+operacion+";"+estado);
    //-------------------------------------------
    
     }catch(Exception e){
         JOptionPane.showMessageDialog(null, "Debe ingresar un numero para elevar"+String.valueOf(longitud), 
                 "Aviso", ERROR_MESSAGE);
        
     }
    }//GEN-LAST:event_btncosActionPerformed

    private void btnsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsenActionPerformed
        // TODO add your handling code here:
                 try{
         double n1=(double)pila.pop();
     double total=Math.sin(n1);
     txtresultado.setText((String.valueOf(total)));
     txtpila.setText((String.valueOf(total)));
     pila.push(total);
     //longitud=1;
      //------------------------------------------
    dato="Sen (radianes)";
    operacion="Seno";
    estado=txtpila.getText();
    this.setLog(dato+";"+operacion+";"+estado);
    //-------------------------------------------
     }catch(Exception e){
         JOptionPane.showMessageDialog(null, "Debe ingresar un numero para elevar"+String.valueOf(longitud), 
                 "Aviso", ERROR_MESSAGE);
      
     }
    }//GEN-LAST:event_btnsenActionPerformed

    private void btntanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntanActionPerformed
        // TODO add your handling code here:
                 try{
         double n1=(double)pila.pop();
     double total=Math.tan(n1);
     txtresultado.setText((String.valueOf(total)));
     txtpila.setText((String.valueOf(total)));
     pila.push(total);
    // longitud=1;
     //------------------------------------------
    dato="Tan (radianes)";
    operacion="Tangente";
    estado=txtpila.getText();
    this.setLog(dato+";"+operacion+";"+estado);
    //-------------------------------------------
     }catch(Exception e){
         JOptionPane.showMessageDialog(null, "Debe ingresar un numero para elevar"+String.valueOf(longitud), 
                 "Aviso", ERROR_MESSAGE);
         
     }
    }//GEN-LAST:event_btntanActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
        
        Logc log=new Logc();
        log.setVisible(true);
        
        
        
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
        txtpila.setText(null);
        txtnumero.setText(null);
        txtresultado.setText(null);
        longitud=0;
        contador=1;
        dato=null;
        estado="";
        operacion=null;
        for(int i=0;i<log.length;i++){
            log[i]=null;
        }
        //-----------------------
        while(pila.empty()==false){
        //true si sta vacia
        pila.pop();
    }
        //--------------------------
        
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        
        if(txtnumero.getText().length()!=0){
            txtnumero.setText(txtnumero.getText().substring(0, txtnumero.getText().length()-1));
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncos;
    private javax.swing.JButton btndivision;
    private javax.swing.JButton btnmultiplicacion;
    private javax.swing.JButton btnraiz;
    private javax.swing.JButton btnraizx;
    private javax.swing.JButton btnresta;
    private javax.swing.JButton btnsen;
    private javax.swing.JButton btnsuma;
    private javax.swing.JButton btntan;
    private javax.swing.JButton btnx2;
    private javax.swing.JButton btnxn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JButton txtenter;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextField txtpila;
    private javax.swing.JTextField txtresultado;
    // End of variables declaration//GEN-END:variables
}
