/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica2_201602598;

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hector
 */
public class Logc extends javax.swing.JFrame {
DefaultTableModel modelo;

    /**
     * Creates new form Logc
     */
    public Logc() {
        initComponents();
        this.setLocationRelativeTo(null);
        modelo=new DefaultTableModel();
        modelo.addColumn("Dato");
        modelo.addColumn("Operacion");
        modelo.addColumn("Estado");
        this.tabla.setModel(modelo);
        
        //-----------------------------------------------
        int cantidad=tabla.getRowCount();
        for(int j=cantidad-1;j>=0;j--){
            modelo.removeRow(j);
        }
        //------------------------------------------------
        
        for(int i=0;i<Calculadora.log.length;i++){
            
             if(Calculadora.log[i]==null){
              
          }else{
            String dividido=Calculadora.log[i];
            String[] coordenadas=dividido.split(";");
            modelo.addRow(coordenadas);
        }
        }
        
    }
    
    public String[][] Llenar(){
        int filas=modelo.getRowCount();
        int columnas=modelo.getColumnCount();
        String excel[][]=new String[filas][columnas];
        for(int i=0;i<filas;i++){
            for(int j=0;j<columnas;j++){
                excel[i][j]=(String)modelo.getValueAt(i, j);
            }
        }
        return excel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        Guardar = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        lblfondo = new javax.swing.JLabel();

        setTitle("Log");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 580, 220));

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 90, 40));

        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 90, 40));

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/windows_10_green_2-wallpaper-1366x768.jpg"))); // NOI18N
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_VolverActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        
        JFileChooser fc=new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int resultado=fc.showSaveDialog(this);
        if(resultado==JFileChooser.CANCEL_OPTION){
            return;
        }
        File archivo=fc.getSelectedFile();
        try{
            PrintWriter salida=new PrintWriter(new PrintWriter(archivo+".csv"));
            String[][] data=Llenar();
            for(int i=0;i<data.length;i++){
                //salida.print(data[i][0]);
                for(int j=0;j<data[i].length;j++){
                    String word=data[i][j];
                    if(word!=null){
                        //salida.print(";"+word);
                        salida.print(word+";");
                    }else{
                        salida.print(";");
                    }
                }
                salida.println();
            }
            salida.close();
            JOptionPane.showMessageDialog(null, "Archivo Guardado");
        }catch(IOException io){
            
        }
        
    }//GEN-LAST:event_GuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Logc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Logc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Logc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Logc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Logc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Volver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
